// @Get Posts
export const GET_POST_LIST_REQUEST = 'post/GET_POST_LIST_REQUEST'
export const GET_POST_LIST_SUCCESS = 'post/GET_POST_LIST_SUCCESS'
export const GET_POST_LIST_FAILED = 'post/GET_POST_LIST_FAILED'

// @Add Post
export const ADD_POST_REQUEST = 'post/ADD_POST_REQUEST'
export const ADD_POST_SUCCESS = 'post/ADD_POST_SUCCESS'
export const ADD_POST_FAILED = 'post/ADD_POST_FAILED'

// @Edit Post
export const EDIT_POST_REQUEST = 'post/EDIT_POST_REQUEST'
export const EDIT_POST_SUCCESS = 'post/EDIT_POST_SUCCESS'
export const EDIT_POST_FAILED = 'post/EDIT_POST_FAILED'

// @Delete Post
export const DELETE_POST_REQUEST = 'post/DELETE_POST_REQUEST'
export const DELETE_POST_SUCCESS = 'post/DELETE_POST_SUCCESS'
export const DELETE_POST_FAILED = 'post/DELETE_POST_FAILED'

// @Get Post Detail
export const GET_POST_DETAIL_REQUEST = 'post/GET_POST_DETAIL_REQUEST'
export const GET_POST_DETAIL_SUCCESS = 'post/GET_POST_DETAIL_SUCCESS'
export const GET_POST_DETAIL_FAILED = 'post/GET_POST_DETAIL_FAILED'

// @Get Comments
export const GET_COMMENTS_REQUEST = 'post/GET_COMMENTS_REQUEST'
export const GET_COMMENTS_SUCCESS = 'post/GET_COMMENTS_SUCCESS'
export const GET_COMMENTS_FAILED = 'post/GET_COMMENTS_FAILED'

// @Add Comments
export const ADD_COMMENT_REQUEST = 'post/ADD_COMMENT_REQUEST'
export const ADD_COMMENT_SUCCESS = 'post/ADD_COMMENT_SUCCESS'
export const ADD_COMMENT_FAILED = 'post/ADD_COMMENT_FAILED'

// @Edit Comment
export const EDIT_COMMENT_REQUEST = 'post/EDIT_COMMENT_REQUEST'
export const EDIT_COMMENT_SUCCESS = 'post/EDIT_COMMENT_SUCCESS'
export const EDIT_COMMENT_FAILED = 'post/EDIT_COMMENT_FAILED'

// @Delete Comment
export const DELETE_COMMENT_REQUEST = 'post/DELETE_COMMENT_REQUEST'
export const DELETE_COMMENT_SUCCESS = 'post/DELETE_COMMENT_SUCCESS'
export const DELETE_COMMENT_FAILED = 'post/DELETE_COMMENT_FAILED'

export const RESET_STATE = 'post/RESET_STATE'
